
# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.ssh.insert_key = false
   config.vbguest.auto_update = false

  config.vm.define :web_server1 do |wb1|
    wb1.vm.box = "Centosi386.1"
    wb1.vm.network :private_network, ip: "192.168.56.101"

    wb1.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "web_server1" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.install = false
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "apache"
      chef.json = {"apaches":[
        {"server":"Apache1" }
      ]}
    end
  end

  config.vm.define :web_server2 do |wb2|
    wb2.vm.box = "Centosi386.1"
    wb2.vm.network :private_network, ip: "192.168.56.103"
    wb2.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "web_server2" ]
    end
    config.vm.provision :chef_solo do |chef|
      chef.install = false
      chef.cookbooks_path = "cookbooks"
      chef.add_recipe "apache"
      chef.json = {"apaches":[
        {"server":"Apache2" }
      ]}
    end
  end

  config.vm.define :centos_database do |db|
  db.vm.box = "Centosi386.1"
  db.vm.network :private_network, ip: "192.168.56.104"
  db.vm.network "public_network", bridge: "eno1", ip:"192.168.131.103", netmask: "255.255.255.0"
  db.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "centos_database" ]
  end
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
 #   chef.add_recipe "mirror"
    chef.add_recipe "mysql"
  #  chef.json ={"aptmirror" => {"server" => "192.168.131.254"}}
  end
end




 config.vm.define :balanceador do |hp|
   hp.vm.box = "centos1706_v0.2.0"
   hp.vm.network :private_network, ip: "192.168.56.102"
   hp.vm.provider :virtualbox do |vb|
     vb.customize ["modifyvm", :id, "--memory", "1024","--cpus", "1", "--name", "balanceador" ]
   end
   hp.vm.provision :chef_solo do |chef|
     chef.install = false
     chef.cookbooks_path = "cookbooks"
     chef.add_recipe "haproxy"
     chef.json = {
      "web_servers" => [
         {"ip":"192.168.56.101"},
         {"ip":"192.168.56.103"}
     ]}
   end
 end

end
